title: "Better StimulusJS"
theme: just-the-docs
# url: "https://www.betterstimulus.com"
aux_links:
  "Github":
    - "//github.com/julianrubisch/better-stimulus"
repository: "julianrubisch/better-stimulus"
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-avatar
  # - jekyll-feed
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-titles-from-headings
  - jekyll-pwa-plugin
  - jekyll-turbolinks
  - jekyll-last-modified-at
sass:
  style: compressed
relative_links:
  enabled:     true
  collections: true
# ga_tracking: UA-159938381-1
pwa:
  dest_js_directory: assets/js
  enabled: true
turbolinks:
  url: /turbolinks.js
