# This is the actual configuration file for litestream.
#
# You can either use the generated `config/initializers/litestream.rb`
# file to configure the litestream-ruby gem, which will populate these
# ENV variables when using the `rails litestream:replicate` command.
#
# Or, if you prefer, manually manage ENV variables and this configuration file.
# In that case, simply ensure that the ENV variables are set before running the
# `replicate` command.
#
# For more details, see: https://litestream.io/reference/config/
dbs:
  - path: storage/production.sqlite3
    replicas:
      - type: s3
        bucket: $LITESTREAM_REPLICA_BUCKET
        path: storage/production.sqlite3
        access-key-id: $LITESTREAM_ACCESS_KEY_ID
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
  - path: storage/development-queue.sqlite3
    replicas:
      - type: s3
        bucket: $LITESTREAM_REPLICA_BUCKET
        path: storage/development-queue.sqlite3
        access-key-id: $LITESTREAM_ACCESS_KEY_ID
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
  - path: storage/development-cache.sqlite3
    replicas:
      - type: s3
        bucket: $LITESTREAM_REPLICA_BUCKET
        path: storage/development-cache.sqlite3
        access-key-id: $LITESTREAM_ACCESS_KEY_ID
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
  - path: storage/development-cable.sqlite3
    replicas:
      - type: s3
        bucket: $LITESTREAM_REPLICA_BUCKET
        path: storage/development-cable.sqlite3
        access-key-id: $LITESTREAM_ACCESS_KEY_ID
        secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY
